### PR TITLE
Fixing PN532 to work with SPI 

### LINKED ISSUE #1292: SPI: Unhandled exception. System.Exception: Can't find a PN532
**Describe the bug**
Hello Team,

thanks a lot for your really great work here.
I However have one problem I've no idea how to solve and am thus asking for help.

I Can't instantiate PN532 with the message of the title.
The module I use is the [Waveshare PN532 Hat](https://www.waveshare.com/wiki/PN532_NFC_HAT#Raspberry_Pi_examples) 
The [DemoCodes](https://www.waveshare.com/w/upload/6/67/Pn532-nfc-hat-code.7z) appear to work:

<sampleOutput>

```bash
Found PN532 with firmware version: 1.6
Waiting for RFID/NFC card...
................Found card with UID: ['0x4', '0x84', '0x81', '0x6a', '0xda', '0x48', '0x80']
................Found card with UID: ['0x4', '0x83', '0x86', '0x6a', '0x8d', '0x5b', '0x80']
................Found card with UID: ['0x4', '0x33', '0x8b', '0x2', '0xa1', '0x5d', '0x80']
```

</sampleOutput>

**Steps to reproduce**

```csharp
using System;
using System.Device.Spi;
using Iot.Device.Pn532;
using Iot.Device.Pn532.ListPassive;

namespace PiNfc
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var device = new Pn532(SpiDevice.Create(new SpiConnectionSettings(0)));

            if (!(device.FirmwareVersion?.IsPn532 ?? false))
            {
                Console.WriteLine("No PN532 detected... return");
                return;
            }
            
            Console.WriteLine($"Firmware: {device.FirmwareVersion}");
            Console.WriteLine($"Version: {device.FirmwareVersion.Version}");
            Console.WriteLine($"Supported cards: {device.FirmwareVersion.VersionSupported}");
        }
    }
}
```

**Expected behavior**

I at least had hoped to read the desfire chip i put on top of the reader.

**Actual behavior**

System.Exception *Can't find a PN532* thrown inside the Constructor of PN532

**Versions used**

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>   
    <PackageReference Include="Iot.Device.Bindings" Version="1.1.0" />   
    <PackageReference Include="System.Device.Gpio" Version="1.1.0" />
  </ItemGroup>

</Project>
```

Dotnet info of machine that is building and runnning the application:
```bash
pi@doorPi:~/tools/PiNfc $ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fixes #1292
- Fixes bug into TryDecode106kbpsTypeA function introduced during nullability migration
- Improving sample with example for each interface
- Adjusting documentation

### CODE REVIEW

File: src/devices/Pn532/Pn532.cs [hunk 1]
```diff
@@ -152,12 +154,17 @@ public Pn532(string portName, LogLevel logLevel = LogLevel.None)
...
+        /// <param name="controller">A GPIO controller</param>
         /// <param name="logLevel">The log level</param>
-        public Pn532(SpiDevice spiDevice, LogLevel logLevel = LogLevel.None)
+        /// <param name="shouldDispose">Dispose the GPIO Controller at the end</param>
+        public Pn532(SpiDevice spiDevice, int pinChipSelect, GpioController? controller = null, LogLevel logLevel = LogLevel.None, bool shouldDispose = false)
         {
             LogLevel = logLevel;
             _spiDevice = spiDevice ?? throw new ArgumentNullException(nameof(spiDevice));
-            _controller = new GpioController();
+            _shouldDispose = shouldDispose | controller == null;
```
Comment (krwq) [inline src/devices/Pn532/Pn532.cs:165]:
```suggestion
            _shouldDispose = shouldDispose || controller == null;
```

File: src/devices/Pn532/Pn532.cs [hunk 2]
```diff
@@ -152,12 +154,17 @@ public Pn532(string portName, LogLevel logLevel = LogLevel.None)
...
+            _controller = controller ?? new GpioController();
+            _pin = pinChipSelect > 0 ? pinChipSelect : throw new ArgumentException($"Pin ChipSelect can only be positive");
```
Comment (krwq) [inline src/devices/Pn532/Pn532.cs:167]: I'd recommend just check for "not -1", I assume for board numbering they might start numbering with 0, likely even logical numbering could start from 0

File: src/devices/Pn532/Pn532.cs [hunk 3]
```diff
@@ -2058,8 +2076,8 @@ private bool IsReady()
             if (_spiDevice is object && _controller is object)
             {
                 _controller.Write(_pin, PinValue.Low);
-                _spiDevice.WriteByte(ReadStatus);
-                ret = _spiDevice.ReadByte();
+                _spiDevice.WriteByte(ReverseByte(ReadStatus));
```
Comment (krwq) [inline src/devices/Pn532/Pn532.cs:2079]: if you always need to reverse byte I'd recommend to enforce DataFlow.LsbFirst instead in the constructor

Comment (Ellerbach) [reply src/devices/Pn532/Pn532.cs:2079]: The thing is that Mod0 and Lbs first is not working on Raspberry Pi. So if this mode is reinforced, it will just crash. So I disregard the value and prefer people not to worry about it

File: src/devices/Pn532/Pn532.cs (hunk 2 above)
Comment (Ellerbach) [reply src/devices/Pn532/Pn532.cs:167]: good catch. I should actually check >=0 as anything negative is bad

File: src/devices/Pn532/Pn532.cs (hunk 3 above)
Comment (krwq) [reply src/devices/Pn532/Pn532.cs:2079]: :( we should fix that, if not supported by driver then do it with software

Comment (krwq) [reply src/devices/Pn532/Pn532.cs:2079]: (out of scope for this PR)

Comment (krwq) [reply src/devices/Pn532/Pn532.cs:2079]: https://github.com/dotnet/iot/issues/1308

File: src/devices/Pn532/Pn532.cs [hunk 4]
```diff
@@ -9,6 +9,7 @@
 using System.Device.Spi;
 using System.IO;
 using System.IO.Ports;
+using System.Security.Cryptography.X509Certificates;
```
Comment (krwq) [inline src/devices/Pn532/Pn532.cs:12]: do you need x509 certs?

Comment (krwq) [reply src/devices/Pn532/Pn532.cs:12]:
```suggestion
```

**Review by krwq — APPROVED** [review]

File: src/devices/Pn532/Pn532.cs (hunk 4 above)
Comment (Ellerbach) [reply src/devices/Pn532/Pn532.cs]: Good catch...
