### PR TITLE
Fixing Hcsr04 issues

### LINKED ISSUE #1179: Hcsr04 TrickCount bug so waiting conditions not respected
**Describe the bug**

Miss usage of ```Environment.TickCount``` which returns a tick count and not milliseconds.
See here and all the following line from this function:
https://github.com/dotnet/iot/blob/3c4034781d158b26be0bc4866c34192d86bc4ef1/src/devices/Hcsr04/Hcsr04.cs#L93
Environment.TickCount:
https://docs.microsoft.com/en-us/dotnet/api/system.environment.tickcount?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Environment.TickCount);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.1

**Steps to reproduce**

So the code is actually not working depending on the platform used

**Expected behavior**

Should use ```(DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond)``` or equivalent instead of ```Environment.TickCount```

**Versions used**

Version from repo with raw code

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fixes #1179 and #1180
- Using DelayHelpers

### CODE REVIEW

File: src/devices/Hcsr04/Hcsr04.cs [hunk 1]
```diff
@@ -66,7 +68,7 @@ public Hcsr04(int triggerPin, int echoPin, PinNumberingScheme pinNumberingScheme
         /// <summary>
         /// Gets the current distance in cm.
```
Comment (krwq) [inline src/devices/Hcsr04/Hcsr04.cs:69]: unit should be removed from description since you change return type

File: src/devices/Hcsr04/Hcsr04.cs [hunk 2]
```diff
@@ -77,7 +79,7 @@ private double GetDistance()
             {
                 if (TryGetDistance(out double result))
```
Comment (krwq) [inline src/devices/Hcsr04/Hcsr04.cs:80]: nit: I'd vote for TryGetDistance to return Length directly

File: src/devices/Hcsr04/Hcsr04.cs [hunk 3]
```diff
@@ -90,39 +92,39 @@ private bool TryGetDistance(out double result)
...
-                Thread.Sleep(TimeSpan.FromMilliseconds(Environment.TickCount - _lastMeasurment));
+                Thread.Sleep(TimeSpan.FromTicks(DateTime.Now.Ticks - _lastMeasurment));
             }
 
+            _lastMeasurment = DateTime.Now.Ticks;
+
             // Trigger input for 10uS to start ranging
             _controller.Write(_trigger, PinValue.High);
-            Thread.Sleep(TimeSpan.FromMilliseconds(0.01));
+            DelayHelper.DelayMicroseconds(10, true);
```
Comment (krwq) [inline src/devices/Hcsr04/Hcsr04.cs:109]: 👍

File: src/devices/Hcsr04/Hcsr04.cs [hunk 4]
```diff
@@ -90,39 +92,39 @@ private bool TryGetDistance(out double result)
...
             _controller.Write(_trigger, PinValue.Low);
 
             // Wait until the echo pin is HIGH (that marks the beginning of the pulse length we want to measure)
             while (_controller.Read(_echo) == PinValue.Low)
             {
-                if (Environment.TickCount - hangTicks > 0)
+                if (DateTime.Now.Ticks - hangTicks > 0)
```
Comment (krwq) [inline src/devices/Hcsr04/Hcsr04.cs:115]: perhaps we should add GetTicks (with inlining) to DelayHelpers in case we need to do this more often in the future and also have a way to convert ticks to seconds. The original code is fine here but seems it's not supported on nano. Also note that DateTime.Now will likely be broken if someone changes system time while app is running

File: src/devices/Hcsr04/samples/README.md [hunk 5]
```diff
@@ -12,16 +12,21 @@
...
 ## Code
 ```C#
 using (var sonar = new Hcsr04(4, 17))
 {
-    while (true)
+    try
     {
-        Console.WriteLine($"Distance: {sonar.Distance} cm");
-        Thread.Sleep(1000);
+        Console.WriteLine($"Distance: {sonar.Distance.Centimeters} cm");
```
Comment (krwq) [inline src/devices/Hcsr04/samples/README.md:23]: we might want to make TryGetDistance public just to avoid this anti-pattern of catching

File: src/devices/Hcsr04/Hcsr04.cs (hunk 2 above)
Comment (Ellerbach) [reply src/devices/Hcsr04/Hcsr04.cs:80]: done

File: src/devices/Hcsr04/Hcsr04.cs (hunk 3 above)
Comment (Ellerbach) [reply src/devices/Hcsr04/Hcsr04.cs:109]: I have a commit delay :-) That was fixed as well! forgot to save the file originally!

File: src/devices/Hcsr04/Hcsr04.cs (hunk 4 above)
Comment (Ellerbach) [reply src/devices/Hcsr04/Hcsr04.cs:115]: If someone will change the time, it's fine, it will just break 1 measure. Not a big deal :-) None of the sensors are perfect. They all can return wrong values time to time. This sensor has multiple retry because of the quality of the measurement anyway.
And same, I already changed the element but didn't save before pushing.

File: src/devices/Hcsr04/samples/README.md (hunk 5 above)
Comment (Ellerbach) [reply src/devices/Hcsr04/samples/README.md:23]: yes, made the Try public and adjusted the sample. Will leave the GetDistance() and Distance public anyway

**Review by krwq — APPROVED** [review]

File: src/devices/Hcsr04/samples/README.md [hunk 6]
```diff
@@ -12,16 +12,22 @@
...
-The fritz diagram above depicts how you should wire your RPi in order to run the program, the resistance for R1 is 1kOhm. (Optional)
+The fritz diagram above depicts how you should wire your RPi in order to run the program, the resistance for R1 is 1kOhm. (Optional).
 
 ## Code
 ```C#
 using (var sonar = new Hcsr04(4, 17))
 {
-    while (true)
+    var res = sonar.TryGetDistance(out Length distance);
+    if (res)
```
Comment (krwq) [inline src/devices/Hcsr04/samples/README.md:22]:
```suggestion
    if (sonar.TryGetDistance(out Length distance))
```

Comment (krwq) [reply src/devices/Hcsr04/samples/README.md:22]: (optional)

**Comment by krwq** [comment]
LGTM, thanks @Ellerbach!
