### PR TITLE
Pressure to altitude conversion fixed

### LINKED ISSUE #2481: WeatherHelper.CalculateAltitude is incorrect
**Describe the bug**

It seems I messed up the formula for calculating the altitude from the current pressure. 

**Steps to reproduce**

Compare with Wikipedia

**Expected behavior**

Results are same

**Actual behavior**

Results are off

**Versions used**

4.1.0

### PR DESCRIPTION
**Pull request by pgrawehr**
Fixes #2481 

The formula had a typo, which resulted in values being off around 10%.

The change is breaking, because one overload was removed, as it technically doesn't make sense. 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/iot/pull/2483)

### CODE REVIEW

File: src/devices/Common/Iot/Device/Common/WeatherHelper.cs [hunk 1]
```diff
@@ -191,47 +199,56 @@ public static RelativeHumidity GetRelativeHumidityFromActualAirTemperature(Tempe
...
         /// <param name="pressure">The pressure at the point for which altitude is being calculated</param>
-        /// <param name="seaLevelPressure">The sea-level pressure</param>
         /// <param name="airTemperature">The dry air temperature at the point for which altitude is being calculated</param>
         /// <returns>The altitude</returns>
-        public static Length CalculateAltitude(Pressure pressure, Pressure seaLevelPressure, Temperature airTemperature)
-        {
-            double meters = ((Math.Pow(seaLevelPressure.Pascals / pressure.Pascals, 1 / 5.255) - 1) * airTemperature.Kelvins) / DefaultTemperatureGradient;
-            return Length.FromMeters(meters);
-        }
+        [Obsolete("Behavior is confusing. Use CalculateAltitude(Pressure, Pressure, Temperature) instead")]
```
Comment (krwq) [inline src/devices/Common/Iot/Device/Common/WeatherHelper.cs]: remove or unobsolete

**Review by krwq — APPROVED** [review]
