### PR TITLE
Fixing documentation for Grove RGB

### LINKED ISSUE #1265: Documentation for CharacterLcd not up to date
Documentation of main Readmed for CharacterLcd is not up to date.
Refer to #1264 
The bindings has been adjusted and LcdRgb1602 is now replaced by LcdRgb which takes new arguments.

This is not correct:

```csharp
var i2cLcdDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x3E));
var i2cRgbDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x62));
using (var lcd = new LcdRgb1602(i2cLcdDevice, i2cRgbDevice))
{
    lcd.Write("Hello World!");
    lcd.SetBacklightColor(Color.Azure);
}
```

Correct should be:

```csharp
var i2cLcdDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x3E));
var i2cRgbDevice = I2cDevice.Create(new I2cConnectionSettings(busId: 1, deviceAddress: 0x62));
using (var lcd = new LcdRgb(new System.Drawing.Size(16, 2), i2cLcdDevice, i2cRgbDevice))
{
    lcd.Write("Hello World!");
    lcd.SetBacklightColor(Color.Azure);
}
```

Also, the samples does not contain any Grove RGB Display, would be nice to add it.

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fixes #1265 
- Related to #1264

### CODE REVIEW

File: src/devices/CharacterLcd/samples/Program.cs [hunk 1]
```diff
@@ -52,3 +52,14 @@ void UsingHd44780OverI2C()
     LcdConsoleSamples.WriteTest(hd44780);
     ExtendedSample.Test(hd44780);
 }
+
+void UsingGroveRgbDisplay()
```
Comment (krwq) [inline src/devices/CharacterLcd/samples/Program.cs:56]: I can't get used to this namespaceless but I like it :)

**Review by krwq — APPROVED** [review]
Thanks!

**Review by pgrawehr — APPROVED** [review]
