### PR TITLE
Avoid the unreliable SYS_TRIGGER-based chip reset.

### LINKED ISSUE #777: Do not use SYS_TRIGGER reset on BNO055
**Describe the bug**

According to Bosch, some BNO055 have soft-reset issues and only work with Power On Reset.
[Writing 0x20 to SYS_TRIGGER](https://github.com/dotnet/iot/blob/2440c17a6a1ba274b250ac5863bccae7f2ecc084/src/devices/Bno055/Bno055Sensor.cs#L129) might render it unusable.

https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BNO055-power-on-reset-issues/m-p/8457/highlight/true#M948

**Steps to reproduce**
Depends on the individual part.
```csharp
new Bno055Sensor(…);
```
or
```bash
# i2cdetect 1
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x03-0x77.
Continue? [Y/n]
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- 28 -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
# i2cset 1 0x28 0x3f 0x20
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will write to device file /dev/i2c-1, chip address 0x28, data address
0x3f, data 0x20, mode byte.
Continue? [Y/n]
# i2cdetect 1
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x03-0x77.
Continue? [Y/n]
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Expected behavior**

Chip continues to work.

**Actual behavior**

Chip vanishes from I²C

### PR DESCRIPTION
**Pull request by Tragetaschen**
Fixes #777

I've decided to overwrite all the writable registers in page 0 with their default values according to the data sheet. This means, there's a change in behavior: Prior to this change, the calibration data would remain active between consecutive runs as long as you didn't change the temperature source (which was the trigger for the chip reset). With this change, that data is reset to default values every time you construct a new BNO055 driver.

I tested this on our custom board by reading the Gravity vector.

### CODE REVIEW

File: src/devices/Bno055/Bno055Sensor.cs [hunk 1]
```diff
@@ -123,24 +123,37 @@ public Bno055Sensor(I2cDevice i2cDevice, OperationMode operationMode = Operation
...
-                PowerMode = PowerMode.Normal;
-                WriteReg(Registers.SYS_TRIGGER, 0x00);
-                TemperatureSource = TemperatureSource.Gyroscope;
+            _operationMode = operationMode;
+            initializeRegisters();
+        }
+
+        private static readonly byte[][] registerDefaults =
+        {
+            new byte[]{ (byte)Registers.UNIT_SEL, (byte)(Units.AccelerationMeterPerSecond | Units.AngularRateDegreePerSecond | Units.DataOutputFormatWindows | Units.EulerAnglesDegrees | Units.TemperatureCelsius) },
```
Comment (krwq) [inline src/devices/Bno055/Bno055Sensor.cs]: nit: space after `[]`

also please try to split long lines into multiple

File: src/devices/Bno055/Bno055Sensor.cs [hunk 2]
```diff
@@ -123,24 +123,37 @@ public Bno055Sensor(I2cDevice i2cDevice, OperationMode operationMode = Operation
...
-                // Need 650 milliseconds after reset
-                Thread.Sleep(650);
-                PowerMode = PowerMode.Normal;
-                WriteReg(Registers.SYS_TRIGGER, 0x00);
-                TemperatureSource = TemperatureSource.Gyroscope;
+            _operationMode = operationMode;
+            initializeRegisters();
+        }
+
+        private static readonly byte[][] registerDefaults =
```
Comment (krwq) [inline src/devices/Bno055/Bno055Sensor.cs]: static should be names as i.e. `s_defaultRegisterValues`

File: src/devices/Bno055/Bno055Sensor.cs [hunk 3]
```diff
@@ -123,24 +123,37 @@ public Bno055Sensor(I2cDevice i2cDevice, OperationMode operationMode = Operation
...
+        };
+
+        private void initializeRegisters()
+        {
+            // WriteReg(Registers.SYS_TRIGGER, 0x20);
+            // Using the chip's internal reset might not work:
+            // https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BNO055-power-on-reset-issues/m-p/8457/highlight/true#M948
+
+            SetConfigMode(true);
+            foreach (var registerDefault in registerDefaults)
```
Comment (krwq) [inline src/devices/Bno055/Bno055Sensor.cs]: use `{` `}` and add extra enter after closing brace

**Comment by krwq** [comment]
@Tragetaschen LGTM after fixing comments.

> Prior to this change, the calibration data would remain active between consecutive runs..

Do you mean that calibration data is cleared after Reset? If so then that's what I'd expect Reset would do.

**Comment by Tragetaschen** [comment]
> > Prior to this change, the calibration data would remain active between consecutive runs..
> 
> Do you mean that calibration data is cleared after Reset? If so then that's what I'd expect Reset would do.

No, if you didn't change the temperature source, the calibration data would be untouched in consecutive runs as there was no reset in that case. With the change, it's always reset to 0.

File: src/devices/Bno055/Bno055Sensor.cs (hunk 1 above)
Comment (Tragetaschen) [reply src/devices/Bno055/Bno055Sensor.cs]: I wish, Roslyn would auto-format those...

File: src/devices/Bno055/Bno055Sensor.cs [hunk 4]
```diff
@@ -123,24 +123,47 @@ public Bno055Sensor(I2cDevice i2cDevice, OperationMode operationMode = Operation
...
+            },
+            new byte[] { (byte)Registers.ACCEL_OFFSET_X_LSB,
+                0, 0, 0, 0, 0, 0, // ACC_OFFSET_*_*SB
+                0, 0, 0, 0, 0, 0, // MAC_OFFSET_*_*SB
+                0, 0, 0, 0, 0, 0, // GYR_OFFSET_*_*SB
+                0, 0, 0, 0, // *_RADIUS_*SB
+            }
+        };
+
+        private void initializeRegisters()
```
Comment (krwq) [inline src/devices/Bno055/Bno055Sensor.cs]:
```suggestion
        private void InitializeRegisters()
```

Sorry, didn't notice earlier

Comment (Tragetaschen) [reply src/devices/Bno055/Bno055Sensor.cs]: Don't worry about it.
Is there a reason the code style rules are not tracked as errors? Since you are going to enforce them via code review anyways… All my projects do that and I pretty much didn't notice the smudge.

Comment (krwq) [reply src/devices/Bno055/Bno055Sensor.cs]: I guess we haven't enabled them yet. I will create an issue on that.

Comment (krwq) [reply src/devices/Bno055/Bno055Sensor.cs]: https://github.com/dotnet/iot/issues/816

**Comment by krwq** [comment]
Thanks @Tragetaschen! Sorry for the delay, I've been busy in the last 2 weeks and got a bit behind in checking PRs
