### PR TITLE
Do not generate backslashes with device-listing on Windows

### LINKED ISSUE #731: [Tools] Fix tool that generates the device lists to output forward slashes instead of backslash
The tool we use for generating the device listings produces the wrong output when running it on a Windows machine, since it uses forward slashes instead of backslashes. Related #728 #729 

FYI: @garciaolais @krwq

### PR DESCRIPTION
**Pull request by garciaolais**
Fix [#731 ](https://github.com/dotnet/iot/issues/731)

- Now the **README** generation works in Windows and Linux 
- Add category file in **BH1745** and **CARD**

### CODE REVIEW

File: tools/device-listing/device-listing.cs [hunk 1]
```diff
@@ -47,6 +47,8 @@ class Program
             "color",
             "led",
             "spi",
+            "nfc",
```
Comment (krwq) [inline tools/device-listing/device-listing.cs]: fine to have both categories but since they currently have exactly the same bindings just display one of them

File: tools/device-listing/device-listing.cs [hunk 2]
```diff
@@ -210,13 +214,11 @@ private static string GetRelativePathSimple(string path, string parentPath)
...
             if (path.StartsWith(parentPath))
             {
-                int i = parentPath.Length;
-                if (path[i] == '/' || path[i] == '\\')
-                {
-                    i++;
-                }
+                string fileName = Path.GetFileName(path);
+                string dirName = new DirectoryInfo(path).Parent.Name;                    
+                UriBuilder uriBuilder = new UriBuilder(){Path = Path.Combine(dirName, fileName)};
```
Comment (krwq) [inline tools/device-listing/device-listing.cs]: I'd leave this logic as it was since it worked correctly according to the name but instead change the logic for generating links (inside of `GetDeviceListing`) since that is actually incorrect (I'd just to `Replace("\\", "/")` but Uri is fine too - you might want to add utility like `CreateMarkdownLinkFromPath` or similar)

Comment (krwq) [reply tools/device-listing/device-listing.cs]: also nit: space after and before `{` and `}`

Comment (garciaolais) [reply tools/device-listing/device-listing.cs]: I thought about using `Replace("\\", "/")`, but I needed to add logic to know which operating system is running.

File: tools/device-listing/device-listing.cs [hunk 3]
```diff
@@ -47,6 +47,7 @@ class Program
             "color",
             "led",
             "spi",
+            "nfc",
```
Comment (joperezr) [inline tools/device-listing/device-listing.cs]: NIT: can you remove the extra spaces after `"nfc",`

File: tools/device-listing/device-listing.cs [hunk 4]
```diff
@@ -204,19 +206,16 @@ private static string FindRepoRoot(string dir)
...
             if (path.StartsWith(parentPath))
             {
-                int i = parentPath.Length;
-                if (path[i] == '/' || path[i] == '\\')
-                {
-                    i++;
-                }
+                string fileName = Path.GetFileName(path);
+                string dirName = new DirectoryInfo(path).Parent.Name;                    
+                UriBuilder uriBuilder = new UriBuilder(){ Path = Path.Combine(dirName, fileName) };
```
Comment (krwq) [inline tools/device-listing/device-listing.cs]:
```suggestion
                UriBuilder uriBuilder = new UriBuilder() { Path = Path.Combine(dirName, fileName) };
```

File: tools/device-listing/device-listing.cs [hunk 5]
```diff
@@ -91,6 +92,7 @@ class Program
             { "buzzer", null },
             { "gopigo3", null },
             { "grovepi", null },
+            { "nfc", "RFID/NFC modules" },
```
Comment (krwq) [inline tools/device-listing/device-listing.cs]:
```suggestion
            { "nfc", "RFID/NFC modules" },
```

**Comment by krwq** [comment]
LGTM after the last suggestion but I wanted to run the tool on linux against this changeset and double check there is no diff

**Comment by krwq** [comment]
```diff
diff --git a/src/devices/README.md b/src/devices/README.md
index 3af9b4c..617490b 100644
--- a/src/devices/README.md
+++ b/src/devices/README.md
@@ -196,7 +196,7 @@ Our vision: the majority of .NET bindings are written completely in .NET languag

 * [Software implementation of SPI](SoftwareSpi/README.md)

-### RFID modules
+### RFID/NFC modules

 * [PN532 - RFID and NFC reader](Pn532/README.md)
 * [RFID shared elements](Card/README.md)
```

**Comment by krwq** [comment]
@garciaolais seems it's worse right now. While there is no visual diff the permissions of the file changed and it shows whole file as a diff

**Comment by krwq** [comment]
ok I fixed the permission issue on your branch

**Comment by joperezr** [comment]
Thanks for fixing this @garciaolais!
