### PR TITLE
Resolved issue #416 - translating the dht22 bytes to temperature

### LINKED ISSUE #416: Dht22 example doesn't work
I have DHT22 sensors which works normally. I checked that by the default python script from Adafriut. I made a decision to give .net core on rpi platform a try with a simple example from the examples folder. I used Dhtxx example but it doesn't work.

This is my code:
```
using System;
using System.Threading;
using Iot.Device.DHTxx;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello DHT!");

        using (DhtSensor dht = new DhtSensor(26, DhtType.Dht22))
        {
            while (true)
            {
                Console.WriteLine($"Temperature: {dht.Temperature.Celsius} °C, Humidity: {dht.Humidity} %");

                Thread.Sleep(2000);
            }
        }
    }
}
```

Project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IoT.Device.Bindings" Version="0.1.0-prerelease.19251.2" />
    <PackageReference Include="System.Device.Gpio" Version="0.1.0-prerelease.19251.2" />
  </ItemGroup>

</Project>
```
I wasn't able to install System.Device.Gpio and IoT.Device.Bindings by using commands from the main readme.md so I just used the nearest proposed version by dotnet add.

I installed .net core on the rpi by using commands:
```
sudo apt-get install curl libunwind8 gettext
wget https://download.visualstudio.microsoft.com/download/pr/9650e3a6-0399-4330-a363-1add761127f9/14d80726c16d0e3d36db2ee5c11928e4/dotnet-sdk-2.2.102-linux-arm.tar.gz
wget https://download.visualstudio.microsoft.com/download/pr/9d049226-1f28-4d3d-a4ff-314e56b223c5/f67ab05a3d70b2bff46ff25e2b3acd2a/aspnetcore-runtime-2.2.1-linux-arm.tar.gz
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-2.2.102-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet 
export PATH=$PATH:$HOME/dotnet
tar zxf aspnetcore-runtime-2.2.1-linux-arm.tar.gz -C $HOME/dotnet
```
On top of that I wasn't able to run it on rpi without `dotnet publish -r linux-arm` since I get FileNotFoundExceptions and runtime isn't able to find System.Device.Gpio.

The result of the program:
```
pi@raspberrypi:~/publish $ dotnet test_dht22.dll
Hello DHT!
Temperature: NaN °C, Humidity: NaN %
Temperature: NaN °C, Humidity: NaN %
Temperature: NaN °C, Humidity: NaN %

```

I tried other library versions and sometimes got values like 123e-308.

Do I do something wrong or the project isn't ready yet for real usage (only people with deep .net knowledge can use it)?

### PR DESCRIPTION
**Pull request by Rickvanderwaal**
Fixes #416

### CODE REVIEW

File: src/devices/Dhtxx/DhtSensor.cs [hunk 1]
```diff
@@ -294,15 +294,15 @@ private double GetTempDht22()
         {
```
[the remark this answers is not in the document]
Comment (shaggygi) [reply src/devices/Dhtxx/DhtSensor.cs]: > This projects support DHT11, DHT12, DHT21(AM2301), DHT22(AM2302).
> Please rename the existing method GetTempDht22 to GetTempDht12.

I haven't looked at these devices or the current code, but would it be better to create an abstract and just call `GetTemp`?

[the remark this answers is not in the document]
Comment (ZhangGaoxing) [reply src/devices/Dhtxx/DhtSensor.cs]: The current model is not complicated, because there are only four devices and three methods. But I don't have a strong preference on any. 😄

[the remark this answers is not in the document]
Comment (joperezr) [reply src/devices/Dhtxx/DhtSensor.cs]: I agree with @shaggygi, having one abstract method implemented on two different devices would be preferable.

File: src/devices/Dhtxx/DhtSensor.cs [hunk 2]
```diff
@@ -294,15 +294,15 @@ private double GetTempDht22()
...
             if (IsLastReadSuccessful)
             {
-                var temp = _readBuff[2] + (_readBuff[3] & 0x7F) * 0.1;
+                var temp = ((_readBuff[2] & 0x7F) * 256 + _readBuff[3]) * 0.1;
```
[the remark this answers is not in the document]
Comment (Rickvanderwaal) [reply src/devices/Dhtxx/DhtSensor.cs]: you are right. The * 256 part is not necessary here. I just tested it. I will remove that extra step.

File: src/devices/Dhtxx/DhtSensor.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Rickvanderwaal) [reply src/devices/Dhtxx/DhtSensor.cs]: I agree that would be better. I will make a proposal in this PR based on the Strategy Pattern.

[the remark this answers is not in the document]
Comment (Rickvanderwaal) [reply src/devices/Dhtxx/DhtSensor.cs]: I have updated the pull request. Please let me know what you think. Feel free to give feedback.
I tested this version on my Dht22 device on raspberry pi model 3 b+ with raspbian. 
image

@ZhangGaoxing can you do some tests with your devices too?

[the remark this answers is not in the document]
Comment (ZhangGaoxing) [reply src/devices/Dhtxx/DhtSensor.cs]: Sorry, I only have DHT11 and DHT12. But now the results seem to be correct.👍

File: src/devices/Dhtxx/Devices/Dht11Device.cs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+﻿using Iot.Units;
```
Comment (ZhangGaoxing) [inline src/devices/Dhtxx/Devices/Dht11Device.cs]: missing dotnet license

File: src/devices/Dhtxx/Devices/Dht11Device.cs [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+namespace Dhtxx.Devices
+{
+    public class Dht11Device : IDhtDevice
```
Comment (ZhangGaoxing) [inline src/devices/Dhtxx/Devices/Dht11Device.cs]: I think the class should be set to `internal`.😄

File: src/devices/Dhtxx/Devices/Dht22Device.cs [hunk 5]
```diff
@@ -0,0 +1,21 @@
+﻿using Iot.Units;
+
+namespace Dhtxx.Devices
+{
+    public class Dht22Device : IDhtDevice
+    {
+        public double GetHumidity(byte[] readBuff)
+        {
+            return (readBuff[0] * 256 + readBuff[1]) * 0.1;
```
Comment (ZhangGaoxing) [inline src/devices/Dhtxx/Devices/Dht22Device.cs]: readBuff[0] + readBuff[1] * 0.1;

File: src/devices/Dhtxx/DhtSensor.cs [hunk 6]
```diff
@@ -25,24 +25,24 @@ public class DhtSensor : IDisposable
...
 
         /// <summary>
         /// How last read went, <c>true</c> for success, <c>false</c> for failure
         /// </summary>
         public bool IsLastReadSuccessful { get; private set; }
 
+        /// <summary>
+        /// Get the device for which this sensor instance is configured
+        /// </summary>
+        public IDhtDevice Device { get; set; }
```
Comment (ZhangGaoxing) [inline src/devices/Dhtxx/DhtSensor.cs]: private field

File: src/devices/Dhtxx/Devices/Dht22Device.cs (hunk 5 above)
Comment (Rickvanderwaal) [reply src/devices/Dhtxx/Devices/Dht22Device.cs]: @ZhangGaoxing That formula is not working for me with DHT22.
The first 2 bytes (16 bits) of humidity is a 16-bit representation of 10 times the actual humidity value. So when `readBuff[0] = 00000010 (2)` and `readBuff[1] = 10011011 (155)` your formula gives the following output `2 + 155 * 0.1 = 17.5 %`. 

The right humidity should be `0000001010011010 (667) * 0.1 = 66.7 %`.

This can be achieved with the following formulas:
* `(readBuff[0] << 8 | readBuff[1]) * 0.1;`
* `(readBuff[0] * 256 + readBuff[1]) * 0.1;`

I don't know why it is working on the DHT11, do you have any suggestion?

Comment (ZhangGaoxing) [reply src/devices/Dhtxx/Devices/Dht22Device.cs]: You are right. I just read the DHT22 datasheet and found that the formula for calculating the results is different from DHT11.

Comment (Rickvanderwaal) [reply src/devices/Dhtxx/Devices/Dht22Device.cs]: I do have both devices now. Tested with DHT11 and DHT22 and both working fine.

File: src/devices/Dhtxx/DhtSensor.cs [hunk 7]
```diff
@@ -106,7 +80,7 @@ public DhtSensor(int pin, DhtType dhtType, PinNumberingScheme pinNumberingScheme
             _protocol = CommunicationProtocol.OneWire;
             _controller = new GpioController(pinNumberingScheme);
             _pin = pin;
-            _dhtType = dhtType;
+            SetDevice(dhtType);
```
Comment (joperezr) [inline src/devices/Dhtxx/DhtSensor.cs]: Why do we even have a DhtType still, can't we just instead change the constructor to take a IDhtDevice instead? Seems to me that DhtType is not really useful anymore but I may be mistaken.

Comment (joperezr) [reply src/devices/Dhtxx/DhtSensor.cs]: Oh nvm, I just saw that dhtType is simply an enum. I like this new refactoring 👍

File: src/devices/Dhtxx/Devices/IDhtDevice.cs [hunk 8]
```diff
@@ -0,0 +1,15 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using Iot.Units;
+
+namespace Dhtxx.Devices
+{
+    public interface IDhtDevice
```
Comment (joperezr) [inline src/devices/Dhtxx/Devices/IDhtDevice.cs]: I suppose that this is the only two things that all dht devices can do? if there are any Dhtxx that have more functionality than these two things, I would suggest using an abstract base class instead of interface, since abstract base class can add members in the future, but interface can't.

Comment (ZhangGaoxing) [reply src/devices/Dhtxx/Devices/IDhtDevice.cs]: At present, the DHT series sensors only have the function of temperature and humidity, and the DHT series has not been updated in these years. Sensors with other functions are not named DHT by ASAIR. So I think all of them can.

Comment (Rickvanderwaal) [reply src/devices/Dhtxx/Devices/IDhtDevice.cs]: Well i can imagine that we have to add some generic methods for all devices in the future. So an abstract class wouldn’t be an bad idea.

Comment (joperezr) [reply src/devices/Dhtxx/Devices/IDhtDevice.cs]: I'm fine with this as is today, so I'll go ahead and merge in order for people currently hitting an issue with this binding to have a new version that works. We can decide later if we want to have an abstract base class instead of an interface.
